package ec.bigdata.facturaelectronicamovil.modelo;
// Generated 27/01/2016 12:36:28 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {


    private Integer idPerfil;
    private String codigoPerfil;
    private String nombrePerfil;
    private String descripcionPerfil;
    private Boolean estadoPerfil;
    private Set clienteEmpresas = new HashSet(0);
    private Set usuarioAccesos = new HashSet(0);
    private Set permisos = new HashSet(0);

    public Perfil() {
    }

    public Perfil(String codigoPerfil, String nombrePerfil, String descripcionPerfil, Boolean estadoPerfil, Set clienteEmpresas, Set usuarioAccesos, Set permisos) {
        this.codigoPerfil = codigoPerfil;
        this.nombrePerfil = nombrePerfil;
        this.descripcionPerfil = descripcionPerfil;
        this.estadoPerfil = estadoPerfil;
        this.clienteEmpresas = clienteEmpresas;
        this.usuarioAccesos = usuarioAccesos;
        this.permisos = permisos;
    }

    public Perfil(Integer idPerfil, String codigoPerfil, String nombrePerfil, String descripcionPerfil, Boolean estadoPerfil) {
        this.idPerfil = idPerfil;
        this.codigoPerfil = codigoPerfil;
        this.nombrePerfil = nombrePerfil;
        this.descripcionPerfil = descripcionPerfil;
        this.estadoPerfil = estadoPerfil;
    }

    public Integer getIdPerfil() {
        return this.idPerfil;
    }

    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

    public String getCodigoPerfil() {
        return this.codigoPerfil;
    }

    public void setCodigoPerfil(String codigoPerfil) {
        this.codigoPerfil = codigoPerfil;
    }

    public String getNombrePerfil() {
        return this.nombrePerfil;
    }

    public void setNombrePerfil(String nombrePerfil) {
        this.nombrePerfil = nombrePerfil;
    }

    public String getDescripcionPerfil() {
        return this.descripcionPerfil;
    }

    public void setDescripcionPerfil(String descripcionPerfil) {
        this.descripcionPerfil = descripcionPerfil;
    }

    public Boolean getEstadoPerfil() {
        return this.estadoPerfil;
    }

    public void setEstadoPerfil(Boolean estadoPerfil) {
        this.estadoPerfil = estadoPerfil;
    }

    public Set getClienteEmpresas() {
        return this.clienteEmpresas;
    }

    public void setClienteEmpresas(Set clienteEmpresas) {
        this.clienteEmpresas = clienteEmpresas;
    }

    public Set getUsuarioAccesos() {
        return this.usuarioAccesos;
    }

    public void setUsuarioAccesos(Set usuarioAccesos) {
        this.usuarioAccesos = usuarioAccesos;
    }

    public Set getPermisos() {
        return this.permisos;
    }

    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }


}


